### ISSUE TITLE
How can I use it with laravel-permission

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-authorize#1]
I am using your laravel-permission package in one of my project and was wondering how does I can use laravel-authorize effectively with that?

**Comment by freekmurze** [comment]
Yep, you can use the two packages together. Each one does a very different thing. 

Laravel's [native authorization functionality](http://laravel.com/docs/5.1/authorization) allows you to define abilities. The [laravel-permission](https://github.com/spatie/laravel-permission) package allows you to store those permissions in the database. It also has support for defining roles. All permissions are registered on [Laravel's Gate](http://laravel.com/docs/5.1/authorization#defining-abilities).

[laravel-authorize](https://github.com/spatie/laravel-authorize) provides a middleware to to protect routes from unauthorized access. It hooks into the abilities that are registered at the Gate.

**Comment by coding-sunshine** [comment]
Thanks. :)

**Comment by Sirlazer2** [comment]
Can you also do role based middlewares then?

Eg. role: admin || role: moderator etc?
