### ISSUE TITLE
Forbidden (403) vs Unauthorized (401)

### ISSUE THREAD

**Issue by vannim152** [spatie/laravel-authorize#10]
Hi all,

Personally, I feel like 403 (Forbidden) is more appropriate [at this line of code](https://github.com/spatie/laravel-authorize/blob/master/src/Middleware/Authorize.php#L102). Can anybody give an explanation why it's not 403 here?

Thanks,

**Comment by freekmurze** [comment]
imo 403 should be used when you unauthenticated (aka not logged in). 401 is for situations that your are logged in, but aren't allowed to do a specific action.

**Comment by vannim152** [comment]
Thanks @freekmurze, I read [this](https://en.wikipedia.org/wiki/HTTP_403#Difference_from_status_.22401_Unauthorized.22) on Wikipedia and it seems like the other way around:

> 403: Authentication was successful, but the authenticated user is not permitted to perform the requested operation

**Comment by freekmurze** [comment]
You're right that most people use 403 for unauthorized actions. It think the description of the 401 should be "unauthenticated". 

Anyways, I changed the behaviour: in v1.1.2 a 403 is returned instead of the 401.

**Comment by vannim152** [comment]
Thanks @freekmurze
