### ISSUE TITLE
permissions based on conditions

### ISSUE THREAD

**Issue by erikbelusic** [spatie/laravel-authorize#2]
@freekmurze continued from twitter =]

i am really trying to figure out how to use laravel-authorize and laravel-permissions together. what i mean is, permissions are defined in a table and then looped through as either yes or no for each role. i am thinking in terms of permissions in the way a CMS like wordpress would handle them.

lets say i wanted to put a permission of can_edit_other_users_posts in the permissions table, and then assign that to a role. i can currently check if a user has that permission based on their role, however, i am unclear where the logic for that would go, as the permission are all looped through and the ability is defined as either yes the user has the permission or no they do not. i guess im asking where the best place to put that logic is?

options ive considered - adding an additional property to permissions that define if its a boolean permission or if its based on conditions. if its boolean, use the current loop to define the abillity. if not, manually define it. the issue is that then some of my abilties only work based on my code.

my other option was to define all permissions in my code in an array of some sort, but i feel like that is just wrong.

can a permission somehow relate to a policy object? not sure if that even comes into play in this situation.

does any of the above make any sense? am i over thinking it?

**Comment by freekmurze** [comment]
Hi,

a permission is nothing more than a db record. The name of the permission wil get registrered at Laravel's Gate. There are [multiple ways](http://laravel.com/docs/5.1/authorization#checking-abilities) to check if a user has a certain permission (or in Laravel parlé a certain ability)

It seems that you are missing some knowledge on how the authorization features of Laravel work. Take a look at the [official documentation](http://laravel.com/docs/5.1/authorization). If it's still a bit unclear read [this excellent post by Matt Stauffer](https://mattstauffer.co/blog/acl-access-control-list-authorization-in-laravel-5-1). Jeffrey Way has posted [an excellent video on the subject](https://laracasts.com/series/whats-new-in-laravel-5-1/episodes/13) on Laracasts.

Check out these resources and take a fresh look at the readme's of this package and laravel-permission. Hopefully things will be less confusing for you. If you still have questions then, don't hesitate to ask!

**Comment by erikbelusic** [comment]
will do. ive seen and read those already, but ill give them a 2nd pass and see if it clears anything up

**Comment by freekmurze** [comment]
Going to close this for now. If you have any more questions just open a new issue.
