### ISSUE TITLE
How to use laravel-permission with laravel-authorize

### ISSUE THREAD

**Issue by acitjazz** [spatie/laravel-authorize#3]
hi.. im newbie in laravel & php and try to learn..

i had create user with permission manage_all  using https://github.com/spatie/laravel-permission

and i tried download this package ,.. and create route like this..
`Route::group(['prefix' => 'backend', 'middleware' => 'can:manage_all'], function() {
  Route::get('/foo', function(){
    return 'view';
  });
});`

but when i open http://localhost:8000/backend/foo  ..  always direct to welcomepage.. 
where is my mistake?

**Comment by freekmurze** [comment]
What do you get when you remove the middleware from the route?

**Comment by acitjazz** [comment]
i got the return 'view' when i remove the middleware

**Comment by freekmurze** [comment]
Can you make sure you are logged in as a user with the `manage_all` permission?

**Comment by acitjazz** [comment]
yes i'm sure `user_id 1` has `permission_id 1`in  table `user_has_permissions`

**Comment by freekmurze** [comment]
Are you logged in as that user?

**Comment by acitjazz** [comment]
yes i'm logged in as that user, 

by the way , i used laravel 5.2 , and sociallite package

**Comment by freekmurze** [comment]
What is the `can` method returning if you try it directly on the user object?

**Comment by acitjazz** [comment]
This my route

`Route::group(['prefix' => 'backend'], function() {
  Route::get('/foo', 'PostController@foo');
});`

and PostController

`public function foo(){
          $user = User::find(1);
          if($user->hasRole('owner')){
            $permissions = $user->permissions;
            return $permissions;
          }
    }`

and the result

`[{"id":1,"name":"manage_all","created_at":"2016-02-13 03:54:27","updated_at":"2016-02-13 03:54:27","pivot":{"user_id":1,"permission_id":1}}]`

**Comment by freekmurze** [comment]
Does replacing the  `$user = User::find(1);`  by  `$user = auth()->user();` render the same results?

If it does, can you try adding a `dd()`-call in permission middleware to verify that it gets called?

**Comment by acitjazz** [comment]
i replacing with`$user = auth()->user();`

the result

`Call to a member function hasRole() on a non-object`
i tried to`dd($user);`
the result is `null`

and a tried again
`$id = Auth::user()->id;
            dd($id);
            $user = User::find($id);`

the result is 
`
ErrorException in PostController.php line 26:
Trying to get property of non-object`

And when i change route using web middleware
`Route::group(['prefix' => 'backend','middleware' => 'web'], function() {
    Route::get('/foo', 'PostController@foo');
});`

the result is  user id `1`

**Comment by acitjazz** [comment]
ooh.. i used middleware group with `web`
`Route::group(['prefix' => 'backend','middleware' => ['web','can:manage_all']], function() {
  Route::get('/foo', 'PostController@foo');
});`
and that is work! 
thanks!
