### ISSUE TITLE
Laravel 5.2 is now /login not /auth/login

### ISSUE THREAD

**Issue by gcphost** [spatie/laravel-authorize#4]
Old
    `return redirect()->guest('auth/login');`

New
        `return redirect()->guest('login');`

Thanks!

**Comment by gcphost** [comment]
Made my own Authorize class as per your directions but would be nice to see it updated for 5.2.

That example needed:
use Symfony\Component\HttpKernel\Exception\HttpException;

**Comment by freekmurze** [comment]
I added the namespace import to the example and will take a look at the code in the coming days.

**Comment by canvural** [comment]
Whats the update on this? Its a simple fix.

**Comment by freekmurze** [comment]
Did not yet have the time to look at this. If you need this quick, submit a PR

**Comment by freekmurze** [comment]
Fixed in version 1.1.0
