### ISSUE TITLE
Laravel 5.2.28 compatibility

### ISSUE THREAD

**Issue by shawnsandy** [spatie/laravel-authorize#7]
Middleware -- can duplicate keys in updated version of Laravel update. Any advice on how to proceed with this? 

``` php
'can' => \Illuminate\Foundation\Http\Middleware\Authorize::class,
'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
'can' => \Spatie\Authorize\Middleware\Authorize::class,
```

**Comment by sebastiandedeyne** [comment]
Laravel has this exact (at least I think exact) functionality built in now.

I'd suggest removing this package if you're on a newer Laravel version and see if everything still works as intended.
