### ISSUE TITLE
Laravel 5.2.28 and up

### ISSUE THREAD

**Issue by gastongr** [spatie/laravel-authorize#8]
This looks like a great addition to the laravel authorization features. 

Just a question, in the readme it says "Do not use in Laravel 5.2.28 and up". I am using the latest version but i couldnt find a middleware to achieve this functionality.

Any advice is welcome.

**Comment by freekmurze** [comment]
L5.2.28 already includes [the middleware](https://github.com/laravel/framework/blob/v5.2.28/src/Illuminate/Foundation/Http/Middleware/Authorize.php). It will be added to the documentation in L5.3.
