### ISSUE TITLE
Authorization error code should be 403

### ISSUE THREAD

**Issue by bioteck** [spatie/laravel-authorize#9]
When a user does not have ability to access a resource, a 401 unauthorized http error is thrown. According to [RFC 7235](https://tools.ietf.org/html/rfc7235), 401 is when it lacks valid authentication credentials for the target resource. However, in this case, this is not a problem with credentials but with permissions. So, shouldn't it be 403?

EDIT: Otherwise, Laravel is using 403 for rendering authorization error:

``` php
// Illuminate\Foundation\Exceptions\Handler::render()

// 5.1
if ($this->isUnauthorizedException($e)) {
    $e = new HttpException(403, $e->getMessage());
}

// 5.2 and 5.3
if ($e instanceof AuthorizationException) {
    $e = new HttpException(403, $e->getMessage());
}
```

**Comment by freekmurze** [comment]
Yup, you're right, a 403 would be better. However, changing the response code is a breaking change. I'm gonna leave this for now. If you're using a modern version of Laravel you don't need the middleware provided by the package and get the right response code.
